title: Etcetera Finances
description: Find all information about the project here
baseurl: "/etcetera-finances" # the subpath of your site, e.g. /blog
url: "https://etchichury.github.io"

remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"

aux_links:
  "Etc. Finances on GitHub":
    - "//github.com/etchichury/etcetera-finances"
